name: checks

on:
  pull_request:
    branches: [main]
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  yaml:
    uses: mathewmusango/my-workflows/.github/workflows/checks-yaml.yml@00bfbcec2e1ebf9662ee7668315aab6af5e66cf7 # v2026.0916.2112
  markdown:
    uses: mathewmusango/my-workflows/.github/workflows/checks-markdown.yml@00bfbcec2e1ebf9662ee7668315aab6af5e66cf7 # v2026.0916.2112
  secrets:
    uses: mathewmusango/my-workflows/.github/workflows/security-secrets.yml@00bfbcec2e1ebf9662ee7668315aab6af5e66cf7 # v2026.0916.2112
  deps:
    uses: mathewmusango/my-workflows/.github/workflows/security-deps.yml@00bfbcec2e1ebf9662ee7668315aab6af5e66cf7 # v2026.0916.2112
